module.exports = [
  "Gummidipoondi", "Ponneri", "Tiruttani", "Tiruvallur", "Poonamallee", "Avadi", "Maduravoyal", "Ambattur", 
  "Madavaram", "Thiruvottiyur", "Dr. Radhakrishnan Nagar", "Perambur", "Kolathur", "Villivakkam", "Thiru-Vi-Ka-Nagar", 
  "Egmore", "Royapuram", "Harbour", "Chepauk-Thiruvallikeni", "Thousand Lights", "Anna Nagar", "Virugampakkam", 
  "Saidapet", "T. Nagar", "Mylapore", "Velachery", "Sholinganallur", "Alandur", "Sriperumbudur", "Pallavaram", 
  "Tambaram", "Chengalpattu", "Thiruporur", "Cheyyur", "Madurantakam", "Uthiramerur", "Kancheepuram", "Arakkonam", 
  "Sholingur", "Katpadi", "Ranipet", "Arcot", "Vellore", "Anaikattu", "K. V. Kuppam", "Gudiyattam", "Vaniyambadi", 
  "Ambur", "Jolarpet", "Tirupattur", "Uthangarai", "Bargur", "Krishnagiri", "Veppanahalli", "Hosur", "Thalli", 
  "Palacode", "Pennagaram", "Dharmapuri", "Pappireddippatti", "Harur", "Chengam", "Tiruvannamalai", "Kilpennathur", 
  "Kalasapakkam", "Polur", "Arani", "Cheyyar", "Vandavasi", "Gingee", "Mailam", "Tindivanam", "Vanur", "Villupuram", 
  "Vikravandi", "Tirukoilur", "Ulundurpettai", "Rishivandiyam", "Sankarapuram", "Kallakurichi", "Gangavalli", 
  "Attur", "Yercaud", "Omalur", "Mettur", "Edappadi", "Sankagiri", "Salem West", "Salem North", "Salem South", 
  "Veerapandi", "Rasipuram", "Senthamangalam", "Namakkal", "Paramathi Velur", "Tiruchengode", "Kumarapalayam", 
  "Erode East", "Erode West", "Modakurichi", "Perundurai", "Bhavani", "Anthiyur", "Gobichettipalayam", "Bhavanisagar", 
  "Dharapuram", "Kangeyam", "Avinashi", "Tiruppur North", "Tiruppur South", "Palladam", "Udumalpet", "Madathukulam", 
  "Udhagamandalam", "Gudalur", "Coonoor", "Mettuppalayam", "Sulur", "Kavundampalayam", "Coimbatore North", 
  "Thondamuthur", "Coimbatore South", "Singanallur", "Kinathukadavu", "Pollachi", "Valparai", "Palani", 
  "Oddanchatram", "Athoor", "Nilakkottai", "Natham", "Dindigul", "Vedasandur", "Aravakurichi", "Karur", 
  "Krishnarayapuram", "Kulithalai", "Manapparai", "Srirangam", "Tiruchirappalli West", "Tiruchirappalli East", 
  "Thiruverumbur", "Lalgudi", "Mannachanallur", "Musiri", "Thuraiyur", "Perambalur", "Kunnam", "Ariyalur", 
  "Jayankondam", "Chidambaram", "Kattumannarkoil", "Cuddalore", "Panruti", "Kurinjipadi", "Bhuvanagiri", 
  "Neyveli", "Vridhachalam", "Tittakudi", "Sirkazhi", "Mayiladuthurai", "Poompuhar", "Nagapattinam", "Kilvelur", 
  "Vedaranyam", "Thiruthuraipoondi", "Mannargudi", "Thiruvarur", "Nannilam", "Thiruvidaimarudur", "Kumbakonam", 
  "Papanasam", "Thiruvaiyaru", "Thanjavur", "Orathanadu", "Pattukkottai", "Peravurani", "Gandharvakottai", 
  "Viralimalai", "Pudukkottai", "Thirumayam", "Alangudi", "Aranthangi", "Karaikudi", "Tiruppattur (Sivaganga)", 
  "Sivaganga", "Manamadurai", "Melur", "Madurai East", "Madurai North", "Madurai Central", "Madurai West", 
  "Madurai South", "Thirupparankundram", "Thirumangalam", "Usilampatti", "Andipatti", "Periyakulam", 
  "Bodinayakanur", "Cumbum", "Theni", "Rajapalayam", "Srivilliputhur", "Sattur", "Sivakasi", "Virudhunagar", 
  "Aruppukkottai", "Tiruchuli", "Paramakudi", "Tiruvadanai", "Ramanathapuram", "Mudukulathur", "Vilathikulam", 
  "Thoothukkudi", "Tiruchendur", "Srivaikuntam", "Ottapidaram", "Kovilpatti", "Sankarankovil", "Vasudevanallur", 
  "Kadayanallur", "Tenkasi", "Alangulam", "Tirunelveli", "Ambasamudram", "Palayamkottai", "Nanguneri", 
  "Radhapuram", "Kanniyakumari", "Nagercoil", "Colachel", "Padmanabhapuram", "Vilavancode", "Killiyoor"
];
